# Generated by Django 5.0.1 on 2024-05-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='roomtype_id',
            new_name='room_type_id',
        ),
        migrations.RenameField(
            model_name='roomtype',
            old_name='roomtype_name',
            new_name='room_type_name',
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(),
        ),
    ]
